### ISSUE TITLE
关于作业提交

### ISSUE THREAD

**Issue by Christian-chen1206** [chenxie95/deeplearning_course_sjtu#18]
请问最终提交的时候，是只需要将源码和报告打包上传Canvas吗。

**Comment by chenxie95** [comment]
> 请问最终提交的时候，是只需要将源码和报告打包上传Canvas吗。

源代码可以打包和报告一起上传到Canvas，也可以告诉我们github public repo路径。同时也需要告诉我们在“交我算”的路径，方便我们直接基于你的环境重现性能。

**Comment by 1115712590** [comment]
请问老师和助教可以直接在同学们的“交我算”路径下运行脚本吗？如果可以是不是只需要提交“交我算”上的代码路径和脚本运行方式就行了？

**Comment by chenxie95** [comment]
> 请问老师和助教可以直接在同学们的“交我算”路径下运行脚本吗？如果可以是不是只需要提交“交我算”上的代码路径和脚本运行方式就行了？

最好把自己相关代码打包一份（只要代码部分），和作业一起上传或放到github公开repo，”交我算“的个人用户路径保留时间有不确定性。
