### ISSUE TITLE
python main.py --model Transformer --cuda and get a user warning

### ISSUE THREAD

**Issue by rujiangyouyou** [chenxie95/deeplearning_course_sjtu#30]
UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance) warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")

Will this affect the model performance?

**Comment by chenxie95** [comment]
It won't affect model performance, only affect the speed. In this LM project, the training and inference is quite fast so it won't bring about related issues.
