### ISSUE TITLE
VAE任务中的最优化valid数据集的重构误差

### ISSUE THREAD

**Issue by Christian-chen1206** [chenxie95/deeplearning_course_sjtu#4]
请问VAE任务中的最优化valid数据集的**重构误差**，指的是仅仅需要最小化Valid集上的BCE吗，还是说要最小化Loss = BCE+KLD，谢谢。

**Comment by chenxie95** [comment]
在validation上你需要两个loss都看的，使用和训练过程相同的loss计算，当然construction loss可能和你图像重构的质量更相关一些。但一般我们是希望train和valid的loss是相同的，只是train是seen data，valid是用unseen data。
