### ISSUE TITLE
音视频场景识别任务无法安装OpenL3

### ISSUE THREAD

**Issue by Christian-chen1206** [chenxie95/deeplearning_course_sjtu#6]
想要修改特征提取的部分，运行安装OpenL3的命令时会报奇怪的错
```
pip install -r requirements_openl3.txt

ERROR: Could not find a version that satisfies the requirement openl3==0.3.1 (from versions: 0.1.0rc5, 0.1.0rc6, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1)
ERROR: No matching distribution found for openl3==0.3.1
```

之后尝试直接把助教目录~/.conda下的pytorch环境复制过来，似乎也没有安装OpenL3。。

**Comment by wsntxxn** [comment]
"from versions: 0.1.0rc5, 0.1.0rc6, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1"
里面已经有0.3.1了，按理说不该找不到。

**Comment by wsntxxn** [comment]
"from versions: 0.1.0rc5, 0.1.0rc6, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1"
里面有0.3.1，按理说不该找不到
你看看直接pip install openl3==0.3.1可以安装吗

**Comment by wsntxxn** [comment]
刚刚看了下，是网络的问题，你没复制全，前面应该有很长的网络连接错误，我在超算上开了个代理，用这个代理安装环境。
`
export http_proxy="http://127.0.0.1:10802
export https_proxy="http://127.0.0.1:10802
`

**Comment by wsntxxn** [comment]
刚刚看了下，是网络的问题，你没复制全，前面应该有很长的网络连接错误，我在超算上开了个代理，用这个代理安装环境。
`export http_proxy="http://127.0.0.1:10802"`
`export https_proxy="http://127.0.0.1:10802"`

**Comment by Christian-chen1206** [comment]
已解决，谢谢助教
