### ISSUE TITLE
Language model 中要求模型大小问题

### ISSUE THREAD

**Issue by Merealtea** [chenxie95/deeplearning_course_sjtu#7]
题目要求总的模型参数参数量不超过60M,是指尝试的三个模型加起来吗？还是只单个模型的参数？因为好像原来给的参数模型就比较小。还有如果使用新的语言模型是否也要小于60M?

**Comment by chenxie95** [comment]
> 
是指单个模型的参数不要超过60M，给的例子模型比较小，方便大家快速跑实验。最终允许调试各种参数，模型参数总数不超过60M

**Comment by Merealtea** [comment]
谢谢老师

**Comment by Z-MU-Z** [comment]
请问总参数量是指main.py里输出的那个，还是实际储存的大小呢，因为两者是不一样的

**Comment by chenxie95** [comment]
> 请问总参数量是指main.py里输出的那个，还是实际储存的大小呢，因为两者是不一样的

是指main.py中输出的神经网络参数总个数，不是指文件大小
